language: python
addons:
  postgresql: "9.3"
  apt:
    packages:
    - rubygems
services:
  - postgresql
install:
  - gem install foreman
  - cd ~
  - git clone https://github.com/recipehub/recipehub-service
  - psql -c 'create database recipehub_service;' -U postgres
  - cd recipehub-service
  - pip install -r requirements.txt
  - python api.py > api.og  2>&1 &
  - sleep 1
  - cd $TRAVIS_BUILD_DIR
  - pip install -r requirements.txt
  - foreman run python manage.py test
script: make test